server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret

          github:
            client-id: client-id
            client-secret: client-secret

logging:
  level:
    org:
      springframework:
        web:TRACE:
        security:TRACE:
